spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
server:
  max-http-request-header-size: 16KB
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info,health
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
application:
  integration:
    base-url: https://jsonplaceholder.typicode.com
    posts-url: ${application.integration.base-url}/posts
    post-by-id-url: ${application.integration.base-url}/posts/{id}
    post-comments-url: ${application.integration.base-url}/posts/{postId}/comments
    comments-by-post-id-url: ${application.integration.base-url}/comments?postId={postId}
  connection:
    connect-timeout: 5000
    read-timeout: 5000
    write-timeout: 5000
    response-timeout: 5000